### ISSUE TITLE
Send Korean memo Truncated

### ISSUE THREAD

**Issue by aiqinxuancai** [GetScatter/eos-sharp#10]
I found in use that sending memo information in Korean is always truncated.

For example: "hihihi만들어드립니다만들어드립니다다만들어드립니다hihihi"
Show when viewing the transaction:
(Memo: hihihi만들어드립니다만들�)

**Comment by aiqinxuancai** [comment]
`        private static void WriteString(MemoryStream ms, object value)
        {
            string s = (string)value;
            var bytes = Encoding.UTF8.GetBytes(s);
            WriteVarUint32(ms, (UInt32)bytes.Length);

            if (bytes.Length > 0)
                ms.Write(bytes, 0, bytes.Length);
        }`

repair code ↑

**Comment by lookjoil** [comment]
Yes, Chinese truncated too.

**Comment by mmcs85** [comment]
Nice find. https://github.com/GetScatter/eos-sharp/commit/8e037801941ab6fa8ddde0b441bde236b04a3290 fixs it.
