### ISSUE TITLE
The action voting for EOS block producers don't run.

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#11]
`			var result = await eos.CreateTransaction(new EosSharp.Api.v1.Transaction()
			{
				Actions = new List<EosSharp.Api.v1.Action>()
				{
						new EosSharp.Api.v1.Action()
						{
							Account = "eosio",
							Authorization = new List<PermissionLevel>()
							{
								new PermissionLevel() {Actor = "myeosaccount", Permission = "owner" }
							},
							Name = "voteproducer",
							Data =new
							{
								voter = "myeosaccount",
								proxy = "",
								producers =new string[] { "eosbeijingbp", "eoscannonchn" }
							}
						}
				}
			});`

**The above code can run, but if the producers order is changed, it won't run:**

`			var result = await eos.CreateTransaction(new EosSharp.Api.v1.Transaction()
			{
				Actions = new List<EosSharp.Api.v1.Action>()
				{
						new EosSharp.Api.v1.Action()
						{
							Account = "eosio",
							Authorization = new List<PermissionLevel>()
							{
								new PermissionLevel() {Actor = "myeosaccount", Permission = "owner" }
							},
							Name = "voteproducer",
							Data =new
							{
								voter = "myeosaccount",
								proxy = "",
								producers =new string[] { "eoscannonchn", "eosbeijingbp"}
							}
						}
				}
			});`

The EOS mainnet will response "voteproducer eosio_assert_message assertion failure" for this code.

**Comment by mmcs85** [comment]
That is normal the smart contract enforces that the order of BP be in alphabetic order.
