### ISSUE TITLE
Memo doesn't print.

### ISSUE THREAD

**Issue by Stuyk** [GetScatter/eos-sharp#12]
Following the main readme.md the Memo doesn't seem to be printing. You can check under the account 'mirrorserver' on the main net.

**Comment by lookjoil** [comment]
https://eospark.com/MainNet/tx/5b8d8f3abba35afc32aeab55cf86d83aa886250664a72c82a242c860b76a7ffa

**Comment by mmcs85** [comment]
looking at the link is printing?
