### ISSUE TITLE
How to generate an eos private key in C#?

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#16]
I can't find a function to generate an eos private key in eos-sharp.

**Comment by mmcs85** [comment]
added new util method to generate Legacy or R1 keypairs.

https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp.UnitTests/SignUnitTests.cs#L37

**Comment by lookjoil** [comment]
> added new util method to generate Legacy or R1 keypairs.
> 
> https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp.UnitTests/SignUnitTests.cs#L37

Thank you, but the EOS private key is a [Wallet Import Format string](https://en.bitcoin.it/wiki/Wallet_import_format). The method you added is just generate a Secp256 string?
