### ISSUE TITLE
Fails when getting "b1" account

### ISSUE THREAD

**Issue by gordns** [GetScatter/eos-sharp#17]
JsonReaderException: Could not convert string to integer: 499999950150. Path 'net_weight', line 1, position 271.

Will probably also fail on cpu_weight. Should be something larger than Int32.

**Comment by mmcs85** [comment]
This https://github.com/GetScatter/eos-sharp/commit/fcae0cc7eea786956ab835286e110f345e4c6b6b fixs it. Give it a try
