### ISSUE TITLE
I found the bug.

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#18]
The line 146 of EosSharp/Helpers/CryptoHelper.cs should be:

`keyType == "sha256x2" ? SerializationHelper.Combine(new List<byte[]>() { new byte[] { 128 }, key }) : key,`

or it will not return the correct string while keyType == "sha256x2".

**Comment by mmcs85** [comment]
You are right lookjoil. Checked this code:
https://github.com/EOSIO/eosjs-ecc/blob/7ec577cad54e17da6168fdfb11ec2b09d6f0e7f0/src/key_private.js#L50

and for keyType == "sha256x2" it needs to add the extra 128 bytes.

**Comment by mmcs85** [comment]
fixed https://github.com/GetScatter/eos-sharp/commit/3400bf94bfa953eafe951521678a50e31bf85f1e
