### ISSUE TITLE
Report a bug.

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#2]
If transfer 0.1 EOS using EOS.CreateTransaction method, It will transfer 0.0232 EOS. the EOS amount is changed.

**Comment by mmcs85** [comment]
Can you post a example invocation?

**Comment by lookjoil** [comment]
https://eosflare.io/tx/8d043796b0a14d8a5a2f54e6171d63a36932c5245528b59b8102a2fbd261a2ad
https://eosflare.io/tx/2b5e3fc2b9c4cc48c4d9262b6d201d00b41288a8d9e58cdf1849d3acc1eb4d23
I have tried many times. if the amount is 0.1 EOS, it will be changed into 0.0232 EOS.

**Comment by mmcs85** [comment]
How are you invoking eos.CreateTransaction? Like this:

var result = await eos.CreateTransaction(new Transaction()
{
    Actions = new List<Api.v1.Action>()
    {
        new Api.v1.Action()
        {
            Account = "eosio.token",
            Authorization = new List<PermissionLevel>()
            {
                new PermissionLevel() {Actor = "tester112345", Permission = "active" }
            },
            Name = "transfer",
            Data = new { from = "tester112345", to = "tester212345", quantity = "0.1000 EOS", memo = "hello crypto world!" }

        }
    }
});

**Comment by lookjoil** [comment]
Yes, I wrote "0.1000 EOS" in my code. You can test it.

**Comment by mmcs85** [comment]
Ok, I have reproduced it. Will look into

**Comment by mmcs85** [comment]
6e88b28 resolves this issue. Feel free to reopen if another problem arises
