### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by zlnvch** [GetScatter/eos-sharp#20]
Currently, eos sharp is failing on iOS due to the following error:

System.Reflection.Emit is not supported.

This is called by FastMember.TypeAccessor.Create

Unfortunately, for iOS support we need to replace all functions using System.Reflection.Emit.

**Comment by mmcs85** [comment]
Can you try my new fix for this? https://github.com/GetScatter/eos-sharp/commit/db1954c8e4e3f369854b40566295af6451bec2d9

**Comment by znebby** [comment]
Working on iOS now! Thanks so much.
