### ISSUE TITLE
Add support for reverse and ram payer in Get Table

### ISSUE THREAD

**Issue by znebby** [GetScatter/eos-sharp#22]
EOS 1.5.0 made a number of changes to Get Table: https://github.com/EOSIO/eos/releases/tag/v1.5.0
We need to add support for reverse search and showing ram payer.

**Comment by mmcs85** [comment]
add this fix: https://github.com/GetScatter/eos-sharp/commit/e5b09f4cbdd566fccdc12f86a7758c28857c41cf

Give it a try
