### ISSUE TITLE
WriteBool

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#3]
AbiSerializationProvider.WriteBool method should be:
WriteByte(ms, (bool)value ? (byte)1 : (byte)0);
or it will write wrong bytes into MemoryStream.

**Comment by mmcs85** [comment]
https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp/Providers/AbiSerializationProvider.cs#L245

ms.Write(new byte[] { **(byte)value** }, 0, 1);

Converts the value to byte and only writes one byte to the memstream.

**Comment by lookjoil** [comment]
When sending a "delegatebw" transaction, there is a "transfer" parameter, type of "transfer" is bool, and only one byte in memsteam can run or it will throw a exception.

**Comment by mmcs85** [comment]
It should work. Try it and give feedback if is ok. :)
WriteByte will always write 1 byte or throw a exception trying to convert to byte.
