### ISSUE TITLE
a GetBlock bug

### ISSUE THREAD

**Issue by coldicelion** [GetScatter/eos-sharp#34]
hi, i got an error by use the GetBlock api 

request block : **55894564** 

`{"ClassName":"Newtonsoft.Json.JsonReaderException","Message":"Unexpected character encountered while parsing value: {. Path 'new_producers', line 1, position 368.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)\n   at Newtonsoft.Json.JsonTextReader.ReadAsString()\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\n   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\n   at EosSharp.HttpHandler.DeserializeJsonFromStream[TData](Stream stream)\n   at EosSharp.HttpHandler.PostJsonAsync[TResponseData](String url, Object data)\n   at EosSharp.Core.Api.v1.EosApi.GetBlock(GetBlockRequest data)\n   at Stardust.EOS.Hatcher.Workers.DrawWorker.ExecuteAsync(CancellationToken stoppingToken) in /Users/wesley/Documents/Development/NETCore/Developing/Hatcher/Stardust.EOS.Hatcher/Workers/DrawWorker.cs:line 99","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Newtonsoft.Json","WatsonBuckets":null}  
`

**Comment by mmcs85** [comment]
Fixed on this release: https://github.com/GetScatter/eos-sharp/releases/tag/v2.0.8
