### ISSUE TITLE
AesEncrypt throws CryptographicException: 'Specified initialization vector (IV) does not match the block size for this algorithm.'

### ISSUE THREAD

**Issue by Matthew-J-Spencer** [GetScatter/eos-sharp#35]
Steps to reproduce:

`var keyPair = EosSharp.Core.Helpers.CryptoHelper.GenerateKeyPair(); ` 
`var pubKeyBytes = [EosSharp.Core.Helpers.CryptoHelper.PubKeyStringToBytes(keyPair.PublicKey);`         
`var encrypted = EosSharp.Core.Helpers.CryptoHelper.AesEncrypt(pubKeyBytes, "Testing testing");` // The error throws here

Hell, I could be doing this wrong but I couldn't find any documentation on these functions.

**Comment by mmcs85** [comment]
This functions takes a array of atleast 48 bytes.
In detail it uses 32 bytes for key + 16 bytes for IV. the key pairs are only 32 bytes in size.
