### ISSUE TITLE
Type of EosSharp.Api.v1.BlockTransaction.Trx

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#4]
The type of EosSharp.Api.v1.BlockTransaction.Trx is BlockDetailedTransaction, but many times you only get a hash string on "trx" from EOS blockchains while run "Api.GetBlock", and if got a string, the CreateTransaction method will not run.

**Comment by mmcs85** [comment]
Can you give a example of a mainet block with transactions with that structure? Need to find a way to distinguish if the trx is returned packed.

**Comment by lookjoil** [comment]
stdClass Object
(
    [timestamp] => 2018-08-28T15:14:59.500
    [producer] => libertyblock
    [confirmed] => 0
    [previous] => 00ce0c2b851a973ac30b9c74870f42bbc8e252920378f8e42fabd2f7bf4276a5
    [transaction_mroot] => f13eebc65c2e92060973760a3c171c254d7a744ecb1841a0aec2330f497fb576
    [action_mroot] => ecbaa704ec42cfe6163bd3e69a1f0a7ba4a9424fa9719f22c0b336a03a3bd3c5
    [schedule_version] => 305
    [new_producers] => 
    [header_extensions] => Array
        (
        )

    [producer_signature] => SIG_K1_K2w7Nb5RE1Bi2qq3ixw3FaoGLY6XRkF9qkv9odKH6xawJpqA3YruitZgGAuSKGr1KqoWMQV6bnooAVPta6G52CZbaVEx9z
    [transactions] => Array
        (
            [0] => stdClass Object
                (
                    [status] => executed
                    [cpu_usage_us] => 2306
                    [net_usage_words] => 0
                    [trx] => 9eb5cf97229ea060b30f87e3a4c4450d31b24f701e84bbfb657995fd7fd12a13
                )

            [1] => stdClass Object
                (
                    [status] => executed
                    [cpu_usage_us] => 251
                    [net_usage_words] => 13
                    [trx] => stdClass Object
                        (
                            [id] => 78f315c3d304884f7f5e8a6c20304d20f9ec18c25e12d189e7662e2a1950d6f7
                            [signatures] => Array
                                (
                                    [0] => SIG_K1_KVsq2mWMRp5Y8vAaFodVxE5GKwMQsG9cFszGRWeRHQU5zfSiDNJkSBUGxoJp6UxPgJb57QnuEdVzfUzUNs2kxDaMy1GucX
                                )

                            [compression] => none
                            [packed_context_free_data] => 
                            [context_free_data] => Array
                                (
                                )

                            [packed_trx] => c968855b700a0a70b6e500000000017055ce8e6788683c0000000080ac14cf017055ce8ee7e94c4300000000a8ed32320b0a5745204c4f564520424d00
                            [transaction] => stdClass Object
                                (
                                    [expiration] => 2018-08-28T15:22:49
                                    [ref_block_num] => 2672
                                    [ref_block_prefix] => 3853938698
                                    [max_net_usage_words] => 0
                                    [max_cpu_usage_ms] => 0
                                    [delay_sec] => 0
                                    [context_free_actions] => Array
                                        (
                                        )

                                    [actions] => Array
                                        (
                                            [0] => stdClass Object
                                                (
                                                    [account] => blocktwitter
                                                    [name] => tweet
                                                    [authorization] => Array
                                                        (
                                                            [0] => stdClass Object
                                                                (
                                                                    [actor] => chaintwitter
                                                                    [permission] => active
                                                                )

                                                        )

                                                    [data] => stdClass Object
                                                        (
                                                            [message] => WE LOVE BM
                                                        )

                                                    [hex_data] => 0a5745204c4f564520424d
                                                )

                                        )

                                    [transaction_extensions] => Array
                                        (
                                        )

                                )

                        )

                )
        )

    [block_extensions] => Array
        (
        )

    [id] => 00ce0c2c14c1f0653cffb17a70349a1e6ec7e52a91e1b3d39ee587d187e7fd4c
    [block_num] => 13503532
    [ref_block_prefix] => 2058485564
)

**Comment by mmcs85** [comment]
Ok looking at that example I feel that the trx is compressed.

**Comment by mmcs85** [comment]
ee3219fb3b2885776f6b30fd49b57f75e8bcde90 fixs this for the short term so it doesnt crash on this cases.

**Comment by mmcs85** [comment]
Just to add to this issue 
[trx] => 9eb5cf97229ea060b30f87e3a4c4450d31b24f701e84bbfb657995fd7fd12a13
Is a transaction_id_type.
