### ISSUE TITLE
How to generate the public key from a private key in eos-Sharp?

### ISSUE THREAD

**Issue by sachushaji** [GetScatter/eos-sharp#40]
Hi,

I couldn't find much information on how to generate the associated public key if you have a private key with you in eos-sharp. I could only see public/private key pairs being generated only when we make use of generateKeyPair. Is there a functionality to generate public key if you have only the private key with you in eos-sharp?

**Comment by mmcs85** [comment]
You can check it here: https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp.Core/Providers/DefaultSignProvider.cs#L27

Use Secp256K1Manager.GetPublicKey(privKeyBytes, true)
