### ISSUE TITLE
Any one know how to create a new account name using eos-sharp?

### ISSUE THREAD

**Issue by lookjoil** [GetScatter/eos-sharp#9]
I tried to send a "newaccount" transaction, but got "Out of Range" message from EOS node.

**Comment by mmcs85** [comment]
Did a commit with some fixes and a unit test for this.
Owner and active key must be a authority Structure.
Sync the source code.

Something like this should work now.
```csharp
var result = await Eos.CreateTransaction(new Transaction()
{
    Actions = new List<Api.v1.Action>()
    {
        new Api.v1.Action()
        {
            Account = "eosio",
            Authorization = new List<PermissionLevel>()
            {
                new PermissionLevel() {Actor = "tester112345", Permission = "active"}
            },
            Name = "newaccount",
            Data = new {
                creator = "tester112345",
                name = "mynewaccount",
                owner = new {
                    threshold = 1,
                    keys = new List<object>() {
                        new { key = "EOS8Q8CJqwnSsV4A6HDBEqmQCqpQcBnhGME1RUvydDRnswNngpqfr", weight = 1}
                    }
                },
                active = new {
                    threshold = 1,
                    keys = new List<object>() {
                        new { key = "EOS8Q8CJqwnSsV4A6HDBEqmQCqpQcBnhGME1RUvydDRnswNngpqfr", weight = 1}
                    }
                }
            }
        },
        new Api.v1.Action()
        {
            Account = "eosio",
            Authorization = new List<PermissionLevel>()
            {
                new PermissionLevel() { Actor = "tester112345", Permission = "active"}
            },
            Name = "buyrambytes",
            Data = new {
                payer = "tester112345",
                receiver = "mynewaccount",
                bytes = 8192,
            }
        },
        new Api.v1.Action()
        {
            Account = "eosio",
            Authorization = new List<PermissionLevel>()
            {
                new PermissionLevel() { Actor = "tester112345", Permission = "active"}
            },
            Name = "delegatebw",
            Data = new {
                from = "tester112345",
                receiver = "mynewaccount",
                stake_net_quantity = "1.0000 EOS",
                stake_cpu_quantity = "1.0000 EOS",
                transfer = false,
            }
        }
    }
});
```

**Comment by mmcs85** [comment]
Did you get the master latest version? I did a commit to fix those errors.

**Comment by lookjoil** [comment]
Yes, I tested with the master latest version. Have you tested?

**Comment by mmcs85** [comment]
Yes I did.
Created unittest here: https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp.UnitTests/EosUnitTests.cs#L184

If you debug and create a breakpoint and it pass this line:
https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp/Eos.cs#L308

It means the transaction is packed and ready to be sent. The out of range erros is packing the trx.

Please can you show more detail on the exception? Stack trace etc?

**Comment by lookjoil** [comment]
The trx is packed and sent successfully.
"out of range" message is responsed from the EOS mainnet:
{"code":500,"error":{"code":8,"name":"out_of_range_exception","what":"Out of Range","details":[]}

**Comment by lookjoil** [comment]
I have tested https://github.com/GetScatter/eos-sharp/blob/master/EosSharp/EosSharp.UnitTests/EosUnitTests.cs#L184
and got the same error.

**Comment by mmcs85** [comment]
Ok then show me the output information that serializes the exception throw.

**Comment by lookjoil** [comment]
{"code":500,"error":{"code":8,"name":"out_of_range_exception","what":"Out of Range","details":[]},"Message":"引发类型为“EosSharp.Exceptions.ApiErrorException”的异常。","Data":{},"InnerException":null,"TargetSite":{"Name":"MoveNext","AssemblyName":"EosSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","ClassName":"EosSharp.Helpers.HttpHelper+<BuildSendResponse>d__18","Signature":"Void MoveNext()","Signature2":"System.Void MoveNext()","MemberType":8,"GenericArguments":null},"StackTrace":"   在 EosSharp.Helpers.HttpHelper.<BuildSendResponse>d__18.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   在 EosSharp.Helpers.HttpHelper.<SendAsync>d__12.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   在 EosSharp.Helpers.HttpHelper.<PostJsonAsync>d__6`1.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   在 EosSharp.Api.v1.EosApi.<PushTransaction>d__22.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   在 EosSharp.Eos.<CreateTransaction>d__30.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   在 EosSharp.UnitTests.EosUnitTests.<CreateNewAccount>d__12.MoveNext() 位置 D:\\tt\\eos-sharp-master(3)\\eos-sharp-master\\EosSharp\\EosSharp.UnitTests\\EosUnitTests.cs:行号 189","HelpLink":null,"Source":"EosSharp","HResult":-2146233088}

**Comment by mmcs85** [comment]
ok Thank you for your efford. I was getting a out of range inside eos-sharp. But with your exception I can see is now throwing from nodeos. Managed to replicate.

Looking into it.

**Comment by mmcs85** [comment]
This commit fixs this problems https://github.com/GetScatter/eos-sharp/commit/54ff2193f56f56d1310d012ded55556dbcef4926

Check the unit test for a working new version.

**Comment by lookjoil** [comment]
It worked.
Thank you very much.
